version: '3'
services:
  #---------------------------------------
  chat-session-server:
    container_name: chatSessionServer
    build:
      context: ./chatSessionServer
      dockerfile: dockerfile
    #image: nikolaik/python-nodejs:python3.8-nodejs12
    volumes:
      - ../chatSessionServer:/usr/app
    ports:
      - "32000:80"
    working_dir: /usr/app
    #stdin_open: true
    tty: true
  #----------------------------------------
  redis:
    container_name: redis
    image: redis:5.0.8
    ports:
      - "32768:6379" #내컴32768 인도커 6379
    tty: true
  #----------------------------------------
  chatServer1:
    container_name: chatServer1
    image: nikolaik/python-nodejs:python3.8-nodejs12
    volumes:
      - ../chatServer:/usr/app
    ports:
      - "32001:80" #내컴8081 인도커 80
    working_dir: /usr/app
    tty: true


